services:
  bookmarker-db:
    image: 'postgres:14-alpine'
    environment:
      - 'POSTGRES_DB=appdb'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '15432:5432'

