name: Java CI with Maven

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    name: Build bookmarker02-api
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build Spring Boot jar
        run: ./mvnw clean package

      - name: Build with Maven (tests)
        run: ./mvnw -B verify

      - name: Build Docker image with buildpacks
        run: |
          ./mvnw spring-boot:build-image -Dspring-boot.build-image.imageName=${{ secrets.DOCKER_USERNAME }}/bookmarker02-api:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/bookmarker02-api:latest
